"""create user_movies table

Revision ID: 59b2f44f738a
Revises: 8e3f07b9dda5
Create Date: 2026-07-09 13:33:30.785131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b2f44f738a'
down_revision: Union[str, Sequence[str], None] = '8e3f07b9dda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', name='uq_user_movie')
    )
    op.create_index(op.f('ix_user_movies_tmdb_id'), 'user_movies', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_user_movies_user_id'), 'user_movies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_movies_user_id'), table_name='user_movies')
    op.drop_index(op.f('ix_user_movies_tmdb_id'), table_name='user_movies')
    op.drop_table('user_movies')
    # ### end Alembic commands ###
