"""create_user_games_table

Revision ID: 6a4708a84eef
Revises: 59b2f44f738a
Create Date: 2026-07-21 14:42:08.060856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4708a84eef'
down_revision: Union[str, Sequence[str], None] = '59b2f44f738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rawg_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rawg_id', name='uq_user_game')
    )
    op.create_index(op.f('ix_user_games_rawg_id'), 'user_games', ['rawg_id'], unique=False)
    op.create_index(op.f('ix_user_games_user_id'), 'user_games', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_games_user_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_rawg_id'), table_name='user_games')
    op.drop_table('user_games')
    # ### end Alembic commands ###
