"""add external_rating to movies and games models

Revision ID: 8730b4df3e2e
Revises: a6f3ac283b96
Create Date: 2026-08-03 12:24:21.047171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8730b4df3e2e'
down_revision: Union[str, Sequence[str], None] = 'a6f3ac283b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('external_rating', sa.Float(), nullable=True))
    op.add_column('user_movies', sa.Column('external_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_movies', 'external_rating')
    op.drop_column('user_games', 'external_rating')
    # ### end Alembic commands ###
