"""create tier list and tier list item tables

Revision ID: a6f3ac283b96
Revises: 6a4708a84eef
Create Date: 2026-07-21 17:14:56.016505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f3ac283b96'
down_revision: Union[str, Sequence[str], None] = '6a4708a84eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_lists_user_id'), 'tier_lists', ['user_id'], unique=False)
    op.create_table('tier_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_list_id', sa.UUID(), nullable=False),
    sa.Column('user_movie_id', sa.UUID(), nullable=True),
    sa.Column('user_game_id', sa.UUID(), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('(user_movie_id IS NOT NULL AND user_game_id IS NULL) OR (user_movie_id IS NULL AND user_game_id IS NOT NULL)', name='ck_tier_item_single_media_ref'),
    sa.ForeignKeyConstraint(['tier_list_id'], ['tier_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_movie_id'], ['user_movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_list_id', 'user_game_id', name='uq_tierlist_game'),
    sa.UniqueConstraint('tier_list_id', 'user_movie_id', name='uq_tierlist_movie')
    )
    op.create_index(op.f('ix_tier_list_items_tier_list_id'), 'tier_list_items', ['tier_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tier_list_items_tier_list_id'), table_name='tier_list_items')
    op.drop_table('tier_list_items')
    op.drop_index(op.f('ix_tier_lists_user_id'), table_name='tier_lists')
    op.drop_table('tier_lists')
    # ### end Alembic commands ###
